var db = require('../utils/dbconnection'); //reference of dbconnection.js
//var db = require('../utils/dbconnectionHana'); //reference of dbconnection.js
var querystring = require('querystring');
const https = require('https');

var User = {

    getAllUsers: function (callback)
    {
        return db.query("select U.T0002_ID as UserID, U.T0002_User_SurName as User_SurName, U.T0002_User_FirstName as User_FirstName, U.T0024_ID as CompanyID, U.T0002_Primary_Language as Primary_Language, U.T0002_Secondary_Language as Secondary_Language, C.T0024_Name as CompanyName, C.T0037_ID as ComunityID, C.RegionID " +
            ", RC.Name RegionName, C.Division, C.CountryID, CC.Name CountryName, C.TimePeriod, C.IndustryID, " +
            "I.Ind_SubInd Ind_Name, C.SubIndID SIName, C.CurrencyID, Cur.Abbreviation Currency, " +
            "C.T0037_ID OrgLevelID, Com.T0037_Desc as Comm_Desc, UE.T0023_Email as User_Email " +
            "from t0002_ext_users U " +
            "join t0024_companyorglevel C on C.T0024_ID = U.T0024_ID " +
            "join tbl_regioncatalog RC on RC.ID = C.RegionID  " +
            "join tbl_countrycatalog CC on CC.ID = C.CountryID " +
            "join tbl_indsubind I on I.ID = C.IndustryID " +
            "join tbl_indsubind SI on SI.ID = C.SubIndID " +
            "join tbl_currencycatalog Cur on Cur.ID = C.CurrencyID " +
            "join t0037_ve_cust_community Com on Com.T0037_ID = C.T0037_ID  " +
            "join t0023_users_emails UE on UE.T0002_ID = U.T0002_ID", callback);
    },

    login: function (email, pass, callback)
    {
        //return db.query("Select * from task",callback);
        if (true)
        {
            callback(null, { "success": true, "apikey": "test", "first_name": "Tester", "last_name": "Tester" });        
        }
        else
        {
            callback({ "success": false, "err": "Login error" }, null);
        }
    },

    loginSocial: function (email, token, provider, callback) {
      //return db.query("Select * from task",callback);

      var host = "";
      var path = "";
      var headers = "";

      if (provider === 'linkedin') {
        host = 'api.linkedin.com';
        path = '/v1/people/~:(id,firstName,lastName,picture-url,email-address)?format=json';
        headers = { 'oauth_token': token };

      } else if (provider === 'facebook') {
        host = 'graph.facebook.com';
        path = '/v2.12/debug_token?input_token=' + token + '&access_token=590772914602357|645cb3c22e44e3cb5ddb6a8fff3986c4'; // app id  + '|' + secret

      } else if (provider === 'google') {
        host = 'www.googleapis.com';
        path = '/oauth2/v3/tokeninfo?id_token=' + token;
      } 

      if (host !== "") {        

        var options = { method: 'GET', host: host, path: path, headers: headers };

        var req = https.request(options, function (res) {

          res.on('data', (d) => {

            var obj = JSON.parse(d);

            console.log(obj);

            if (provider === 'linkedin') {
              if (obj.hasOwnProperty('errorCode')) {
                callback({ "success": false, "err": obj.message }, null);
              } else {
                if (obj.emailAddress !== email) {
                  callback({ "success": false, "err": "Email does not match" }, null);                  
                } else {
                  // todo - generate api key from db ?
                  callback(null, { "success": true, "apikey": "test", "first_name": "Tester", "last_name": "Tester" });
                }
              }
            } else if (provider === 'facebook') {
              if (obj.error) {
                callback({ "success": false, "err": obj.error.message }, null);
              } else {
                // todo - get email from facebook and compare if it match
                // todo - generate api key from db ?
                callback(null, { "success": true, "apikey": "test", "first_name": "Tester", "last_name": "Tester" });
              }
            } else if (provider === 'google') {
              if (!obj.hasOwnProperty('email')) {
                if (obj.hasOwnProperty('error_description')) {
                  callback({ "success": false, "err": obj.error_description }, null);
                } else {
                  callback({ "success": false, "err": 'Invalid token' }, null);
                }
              } else {
                if (obj.email !== email) {
                  callback({ "success": false, "err": "Email does not match" }, null);
                } else if (obj.uad !== '399849501114-nrc9gogltttgej174aqdeelgdq1bdfne.apps.googleusercontent.com') { // generated by google console for this app
                  callback({ "success": false, "err": "Invalid application" }, null);
                } else {
                  // todo - generate api key from db ?
                  callback(null, { "success": true, "apikey": "test", "first_name": "Tester", "last_name": "Tester" });
                }
              }
            } 
    
          });

        }).on('error', (e) => {
          console.error(e);
          callback({ "success": false, "err": e }, null);
        });

        req.end();
      } else {
        callback({ "success": false, "err": "Invalid provider" }, null);
      }

    },

    validateCaptcha: function (token, callback) {

        var postData = querystring.stringify({
            'secret': '6Ldxtk8UAAAAAPXa0oxqs8Fwf5jNWll9dHAUOtYT',
            'response': token
        });

        var headers = {
            'Content-Type': 'application/x-www-form-urlencoded',
            'Content-Length': postData.length
        };

        var options = { method: 'POST', host: 'google.com', port: 443, path: '/recaptcha/api/siteverify', headers: headers };

        var req = https.request(options, function (res) {

            res.on('data', (d) => {

                var obj = JSON.parse(d);

                console.log(obj);

                // Success will be true or false depending upon captcha validation.
                if (obj.success !== undefined && !obj.success) {
                    callback(null, { "sucess": obj.success, "results": obj['error-codes'] });
                    return;
                }
                callback(null, { "success": obj.success, "results": obj })

            })
            res.on('error', (e) => {
                console.error(e);
                callback({ "success": false, "err": e }, null);
            });
        });

        req.write(postData);
        req.end();
    }
};

module.exports=User;